### ISSUE TITLE
Display disk usage for multiple mountpoints

### ISSUE THREAD

**Issue by retcinder** [AlphaTechnolog/cutefetch#1]
Right now, it only shows the usage for the root.
However, I have 3 different mount locations I'd like to be able to display (`/`, `/home` and a directory in my home folder).
Is there any way cutefetch could add an option to be able to add multiple mountpoints for disk usage listing?

**Comment by AlphaTechnolog** [comment]
Yeah i think it's mostly because of [this line](https://github.com/AlphaTechnolog/cutefetch/blob/38c72c9101054f46ce3f074b47ee0297615f764d/src/disk.c#L12) that i will be able to do it, but i will have to first investigate on how to detect the others mountpoints in order to call that logic for each mountpoint

**Comment by AlphaTechnolog** [comment]
for convenience, can you please share me your /proc/mounts? i would like to see if it's suitable/ez to me to just read it and quickly parse it as needed

**Comment by AlphaTechnolog** [comment]
some advances in this are present in the `feature/multidisk` branch if you wanna test it, anyways im planning on adding a new flag to disable/enable it in case you don't want or want to show the whole disks, looks like this atm:
![image](https://github.com/AlphaTechnolog/cutefetch/assets/54639968/2b0df019-fa66-4a83-9e72-db7dd0d9c000)

**Comment by retcinder** [comment]
> for convenience, can you please share me your /proc/mounts? i would like to see if it's suitable/ez to me to just read it and quickly parse it as needed

Sure, here it is:
```
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sys /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
dev /dev devtmpfs rw,nosuid,relatime,size=6038916k,nr_inodes=1509729,mode=755,inode64 0 0
run /run tmpfs rw,nosuid,nodev,relatime,mode=755,inode64 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
/dev/nvme0n1p2 / ext4 rw,relatime 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev,inode64 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=34,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=15964 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,nosuid,nodev,relatime,pagesize=2M 0 0
debugfs /sys/kernel/debug debugfs rw,nosuid,nodev,noexec,relatime 0 0
tracefs /sys/kernel/tracing tracefs rw,nosuid,nodev,noexec,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
ramfs /etc/pacman.d/gnupg ramfs rw,relatime 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev,size=6045896k,nr_inodes=1048576,inode64 0 0
/dev/nvme0n1p4 /home ext4 rw,relatime 0 0
/dev/nvme0n1p1 /boot/efi vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro 0 0
/dev/mmcblk0p1 /home/tulpenkiste/Documents/Games/Steam ext4 rw,relatime,errors=remount-ro 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=1209176k,nr_inodes=302294,mode=700,uid=1000,gid=1000,inode64 0 0
portal /run/user/1000/doc fuse.portal rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
```

**Comment by retcinder** [comment]
> some advances in this are present in the `feature/multidisk` branch if you wanna test it, anyways im planning on adding a new flag to disable/enable it in case you don't want or want to show the whole disks, looks like this atm: ![image](https://user-images.githubusercontent.com/54639968/277189626-2b0df019-fa66-4a83-9e72-db7dd0d9c000.png)

Just tried it, it works nicely.
![image](https://github.com/AlphaTechnolog/cutefetch/assets/63363329/53c65006-f772-4e21-a6a8-ac9dfe96165a)

**Comment by AlphaTechnolog** [comment]
yep, it's great to see it worked :grin:. I think i will be polishing a little more this changes and merging them into the main branch, but, the next step, will be adding a config file or something to hide multidisk if the user doesn't wants to show every disk.

**Comment by AlphaTechnolog** [comment]
merged to main :)
